--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NoobyPE/CitizenTest
build-by-default: true
branches:
- main
projects:
  CitizenTest:
    path: ""
    lint: 
      phpstan: false
    libs:
      - src: NoobyPE/CitizenLibrary/CitizenLibrary
        version: ^2.2.1
...
