name: CitizenTest
version: 0.0.1
main: iSrDxv\CitizenTest\Main
api: 5.10.0
commands:
  npc:
    description: Example Command
    usage: /npc
    aliases:
      - n
      - citizen
    permission: npc.cmd
    permission-message: "You do not have permission to use this example command!"
permissions:
  npc.cmd:
    default: true
    description: Send NPC
